[tool.poetry]
name = "pqcrypto-fm-integration-tests"
version = "1.0.0"
description = "Integration tests for PQCrypto_FM plugin"

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^7.4.0"
pytest-asyncio = "^0.21.0"
liboqs-python = ">=0.12.0"
requests = "^2.31.0"