# ACA-Py Holder Agent Configuration
# Role: Receive and hold verifiable credentials, generate proofs on cheqd ledger
# Plugins: cheqd (DID method), pqcrypto_fm (Post-Quantum Crypto)

label: "PQC Quantum-Safe Holder on cheqd"
auto-provision: true

#############################################################################
# Plugins Configuration
#############################################################################

plugin:
  - cheqd
  - pqcrypto_fm

plugin-config: /app/cheqd-config.yml
plugin-config-value: /app/pqc-config.yml

#############################################################################
# Transport Configuration
#############################################################################

inbound-transport:
  - [http, 0.0.0.0, 8030]
  - [ws, 0.0.0.0, 8032]

outbound-transport: http

endpoint:
  - http://acapy-holder:8030
  - ws://acapy-holder:8032

#############################################################################
# Admin API Configuration
#############################################################################

admin: [0.0.0.0, 8031]
admin-insecure-mode: true

#############################################################################
# Wallet Configuration (Askar-AnonCreds with PostgreSQL)
#############################################################################

wallet-name: holder_wallet
wallet-type: askar-anoncreds
wallet-key: holder_wallet_key_secure_2024
wallet-storage-type: postgres_storage

wallet-storage-config: |
  {
    "url": "postgres-acapy:5432",
    "wallet_scheme": "DatabasePerWallet"
  }

wallet-storage-creds: |
  {
    "account": "acapy",
    "password": "acapy_secret",
    "admin_account": "acapy",
    "admin_password": "acapy_secret"
  }

wallet-allow-insecure-seed: true

#############################################################################
# Ledger Configuration (cheqd network)
#############################################################################

no-ledger: true

#############################################################################
# Connection & Credential Settings
#############################################################################

# Connection Settings
debug-connections: true
auto-accept-invites: true
auto-accept-requests: true
auto-ping-connection: true
auto-respond-messages: true
monitor-ping: true

# Credential Settings
debug-credentials: true
auto-store-credential: true
auto-respond-credential-proposal: false
auto-respond-credential-offer: true
auto-respond-credential-request: true
preserve-exchange-records: true

# Presentation Settings
debug-presentations: true
auto-respond-presentation-proposal: false
auto-respond-presentation-request: false  # Holder decides when to present
auto-verify-presentation: false  # Holder doesn't verify, only presents

#############################################################################
# Revocation Configuration
#############################################################################

monitor-revocation-notification: true

#############################################################################
# Logging Configuration
#############################################################################

log-level: info
log-file: /tmp/holder.log

#############################################################################
# Performance & Security Settings
#############################################################################

ws-heartbeat: 30
ws-timeout: 60

public-invites: true

emit-new-didcomm-prefix: true
emit-new-didcomm-mime-type: true
